const getWords = () =>{
    let words = ["HELLO", "TIC", "IMAGE", "CORN",
    "WORLD", "BROTHER", "SCHOOL", "COMPUTER",
    "LAPTOP", "WORD", "CONTEST", "MONEY",
    "ALIEN", "RAGE", "BRAVE", "MALE",
    "FEMALE", "GARAGE", "HOUSE", "NOT",
    "NO", "ROW", "CROW", "FLIGHT",
    "MUSIC", "FIGURE", "SCIENCE", "TOURNAMENT",
    "WAR", "BAR", "ALCOHOL", "LEAUGE", 
    "UNEMPLOYED", "FLOOR", "RANDOM", "ELEMENT",
    "ADMISSION", "ADVENTURE", "ATTRACT", "ASSEMBLY",
    "ANT", "ADVERTISE", "ACCOUNTANT", "AVENUE",
    "ALUMINIUM", "AUCTION", "ACTIVITY", "AUTOMATIC",
    "AS", "AT", "ALCOHOL", "BARREL", "BOLT",
    "BELONG", "BUTTON", "BODY", "BLESS", "BLEED", 
    "BELT", "BLOW", "BUFFET", "BAND", "BARK",
    "BREED", "BEDROOM", "BITE", "CRITIC", "COMPOUND",
    "CHANGE", "CRIME", "COUNCIL", "CROSS", "CHARACTERISTIC",
    "CAMP", "CARE", "CONVULSION", "CONSTITUENCY",
    "COLORFUL", "CAMERA", "COLOR", "CIRCULATION", "DEFEAT",
    "DIAGREEMENT", "DEMOCRATIC", "DRINK", "DIAGRAM", "DISAPPOINT",
    "DECIDE", "DENY", "DRY", "DISCOVER", "DISTORT", "DYNAMIC",
    "DAUGHTER", "DETECTIVE", "DEER", "EXTENT", "ERA", "ELITE",
    "EXCEED", "ECONOMIC", "EXCLUSIVE", "ENJOY", "ERUPT", "EGG",
    "EYE", "ELIMINATE", "FOOTBALL", "FINGER", "FEELING", "FLOCK",
    "FULL", "FINANCE", "FAST", "FUNCTION", "FLOOR", "FLOUR"];
    
    return words;
}